### ISSUE TITLE
cli deploy errors due to archive size limit

### ISSUE THREAD

**Issue by andykenward** [grafbase/grafbase#319]
**Describe the bug**
When deploying locally using the npm cli tool `grafbase deploy` an error is thrown of 
`Error: could not deploy as the created archive size is above the allowed limit of 10000000 bytes`. 

This appears to be the `node_modules/grafbase` causing this if it is installed in the `/grafbase` folder.

**To Reproduce**

Add the `grafbase` package to `/grafbase` folder as a `devDependencies`
```
cd grafbase
npm init -y
npm install grafbase -D
npx grafbase deploy
```

**Expected behavior**
Ignore npm packages in the devDependencies `/grafbase/package.json` when running `grafbase deploy`.

**Examples**
See [andykenward/grafbase-with-nextjs-clerk/tree/bug-deploy-size](https://github.com/andykenward/grafbase-with-nextjs-clerk/tree/bug-deploy-size) and try to run `npx grafbase deploy`

**Desktop (please complete the following information):**

- OS: macOS
- Version 13.3.1 
- Node 18.15.0 arm64
- NPM 9.5.0
- Grafbase 0.18.6

**Additional context**

The reason for installing `grafbase` in the `/grafbase` folder is for a Monorepo project using [Turborepo](https://turbo.build/repo). Also to version the cli `grafbase` package to reduce breaking changes.

**Comment by yoav-lavi** [comment]
Hey @andykenward, this should be resolved in `0.18.11`!

**Comment by andykenward** [comment]
> Hey @andykenward, this should be resolved in `0.18.11`!
> Please let us know if you still have any issues

This issue is not fixed for me using `0.18.13`. Still getting the same issue of 
```
Error: could not deploy as the created archive size is above the allowed limit of 10000000 bytes
```

**Comment by yoav-lavi** [comment]
Thanks @andykenward we'll take a look and update

**Comment by yoav-lavi** [comment]
@andykenward this should be resolved now
